import { useMemo, useState } from 'react'

const MODELS = [
  { id: 'claude-fable-5', name: 'Claude Fable 5', provider: 'Anthropic', tier: 'deep', badge: 'Maximum capability', best: 'Hardest, longest, highest-stakes work', copy: 'Use when the task is ambiguous, multi-threaded, or needs sustained autonomy across a large context.', context: '1M tokens', output: '128k max', thinking: 'Adaptive, always on', price: '$10 in / $50 out MTok', pace: 'Deep', session: '30 to 120+ min', speed: 2, overall: 10, value: 5, scores: { code: 10, ui: 10, debug: 10, plan: 10, research: 10, writing: 9 }, tasks: ['hard problem', 'long agent', 'architecture', 'research', 'documents'] },
  { id: 'claude-opus-5', name: 'Claude Opus 5', provider: 'Anthropic', tier: 'deliberate', badge: 'Best Claude default', best: 'Complex coding, UI replication, enterprise work', copy: 'A major step above Opus 4.8 for deep reasoning, agentic coding, visual frontend tasks, and code review.', context: '1M tokens', output: '128k max', thinking: 'On by default', price: '$5 in / $25 out MTok', pace: 'Deliberate', session: '20 to 90 min', speed: 5, overall: 10, value: 7, scores: { code: 10, ui: 10, debug: 10, plan: 10, research: 9, writing: 9 }, tasks: ['code', 'UI / UX', 'debugging', 'long agent', 'enterprise'] },
  { id: 'claude-opus-4-8', name: 'Claude Opus 4.8', provider: 'Anthropic', tier: 'deliberate', badge: 'Proven Opus', best: 'Complex reasoning with an existing stable prompt', copy: 'Still a strong high-autonomy model. Keep it for compatibility or when you specifically want its behavior.', context: '1M tokens', output: '128k max', thinking: 'Effort control', price: '$5 in / $25 out MTok', pace: 'Deliberate', session: '15 to 75 min', speed: 5, overall: 9, value: 7, scores: { code: 9, ui: 9, debug: 9, plan: 9, research: 9, writing: 9 }, tasks: ['code', 'debugging', 'planning', 'long context', 'compatibility'] },
  { id: 'gpt-5.6-sol-high', name: 'GPT-5.6 Sol · high', provider: 'OpenAI', tier: 'deliberate', badge: 'Hard tool work', best: 'Difficult reasoning, tool-heavy coding, agent orchestration', copy: 'Use when a frontier OpenAI model needs to inspect, change, test, and reason through a difficult repo or workflow.', context: 'Surface dependent', output: 'Surface dependent', thinking: 'High effort', price: 'Plan / surface dependent', pace: 'Deliberate', session: '20 to 90 min', speed: 5, overall: 10, value: 8, scores: { code: 10, ui: 9, debug: 10, plan: 10, research: 9, writing: 8 }, tasks: ['code', 'debugging', 'architecture', 'planning', 'agent orchestration'] },
  { id: 'claude-sonnet-5', name: 'Claude Sonnet 5', provider: 'Anthropic', tier: 'fast', badge: 'Speed plus intelligence', best: 'Everyday coding, UI polish, high-volume work', copy: 'The practical Claude workhorse when you need strong output quickly without maximum autonomy.', context: '1M tokens', output: '128k max', thinking: 'Adaptive', price: '$3 in / $15 out MTok', pace: 'Fast', session: '10 to 45 min', speed: 8, overall: 9, value: 9, scores: { code: 9, ui: 9, debug: 9, plan: 8, research: 8, writing: 9 }, tasks: ['code', 'UI / UX', 'refactor', 'writing', 'everyday'] },
  { id: 'gpt-5.6-terra-medium', name: 'GPT-5.6 Terra · medium', provider: 'OpenAI', tier: 'balanced', badge: 'Best everyday default', best: 'Clear, bounded coding, UI polish, product work', copy: 'Use this first when the job is well-scoped and you can quickly verify the result. It keeps quality high without paying for extra deliberation.', context: 'Surface dependent', output: 'Surface dependent', thinking: 'Medium effort', price: 'Plan / surface dependent', pace: 'Balanced / quicker', session: '5 to 25 min', speed: 8, overall: 8, value: 10, scores: { code: 8, ui: 8, debug: 7, plan: 8, research: 8, writing: 9 }, tasks: ['daily default', 'code', 'UI / UX', 'planning', 'product', 'quick edit', 'writing'] },
  { id: 'gpt-5.6-terra-high', name: 'GPT-5.6 Terra · high', provider: 'OpenAI', tier: 'balanced', badge: 'When scope or stakes rise', best: 'Multi-file work, root-cause debugging, careful plans', copy: 'Choose High when a wrong first assumption would cost more than waiting, or when you would otherwise need several correction rounds.', context: 'Surface dependent', output: 'Surface dependent', thinking: 'High effort', price: 'Plan / surface dependent', pace: 'Balanced / deliberate', session: '10 to 45 min', speed: 7, overall: 9, value: 10, scores: { code: 9, ui: 8, debug: 9, plan: 9, research: 8, writing: 9 }, tasks: ['code', 'planning', 'product', 'debugging', 'writing'] },
  { id: 'gpt-5.5', name: 'GPT-5.5', provider: 'OpenAI', tier: 'deliberate', badge: 'Professional work', best: 'Professional coding and knowledge work', copy: 'A capable frontier option for serious work when your environment already routes to GPT-5.5.', context: 'Surface dependent', output: 'Surface dependent', thinking: 'Configurable effort', price: 'Plan / surface dependent', pace: 'Moderate', session: '15 to 60 min', speed: 6, overall: 9, value: 8, scores: { code: 9, ui: 8, debug: 9, plan: 9, research: 9, writing: 9 }, tasks: ['code', 'research', 'planning', 'documents'] },
  { id: 'gpt-5.6-luna', name: 'GPT-5.6 Luna', provider: 'OpenAI', tier: 'fast', badge: 'Fast and efficient', best: 'Small edits, quick drafts, high-volume tasks', copy: 'Use for repetitive work and first passes where speed and cost matter more than maximum depth.', context: 'Surface dependent', output: 'Surface dependent', thinking: 'Cost-sensitive routing', price: 'Plan / surface dependent', pace: 'Fast', session: '5 to 25 min', speed: 9, overall: 8, value: 10, scores: { code: 7, ui: 7, debug: 7, plan: 7, research: 6, writing: 8 }, tasks: ['quick edit', 'draft', 'summarize', 'simple code', 'high volume'] },
  { id: 'gpt-5.4-mini', name: 'GPT-5.4 mini', provider: 'OpenAI', tier: 'fast', badge: 'Small but strong', best: 'Subagents, focused fixes, computer-use helpers', copy: 'A strong small model for bounded jobs that would waste a frontier model time or budget.', context: 'Surface dependent', output: 'Surface dependent', thinking: 'Configurable effort', price: 'Plan / surface dependent', pace: 'Fast', session: '5 to 20 min', speed: 8, overall: 8, value: 10, scores: { code: 8, ui: 7, debug: 8, plan: 7, research: 6, writing: 7 }, tasks: ['subagent', 'quick edit', 'computer use', 'test fix'] },
  { id: 'claude-haiku-4-5', name: 'Claude Haiku 4.5', provider: 'Anthropic', tier: 'fast', badge: 'Fastest Claude', best: 'Simple classification, summaries, transformations', copy: 'Reach for it when the request is clear and bounded, and speed matters more than deep reasoning.', context: '200k tokens', output: '64k max', thinking: 'Extended available', price: '$1 in / $5 out MTok', pace: 'Fastest', session: '3 to 15 min', speed: 10, overall: 7, value: 10, scores: { code: 6, ui: 6, debug: 6, plan: 6, research: 5, writing: 8 }, tasks: ['summarize', 'classify', 'quick edit', 'high volume'] },
  { id: 'gpt-5.3-codex-spark', name: 'GPT-5.3 Codex Spark', provider: 'OpenAI', tier: 'fast', badge: 'Ultra-fast coding', best: 'Tiny coding loops and immediate feedback', copy: 'Best for a narrow change, quick test correction, or interactive loop where waiting is the bottleneck.', context: 'Surface dependent', output: 'Surface dependent', thinking: 'Ultra-fast coding', price: 'Plan / surface dependent', pace: 'Fastest', session: '2 to 12 min', speed: 10, overall: 7, value: 10, scores: { code: 7, ui: 6, debug: 7, plan: 5, research: 4, writing: 6 }, tasks: ['quick edit', 'test fix', 'small code', 'interactive'] },
]

const TASKS = [['daily default', 'Daily default'], ['code', 'Code'], ['UI / UX', 'UI / UX'], ['debugging', 'Debugging'], ['planning', 'Planning'], ['research', 'Research'], ['long agent', 'Long agent'], ['quick edit', 'Quick edit'], ['summarize', 'Summarize']]
const RECOMMENDATIONS = {
  'daily default': ['GPT-5.6 Terra · medium', 'Use Medium when the task is clear. Move to High when the scope, ambiguity, or cost of being wrong rises.'],
  code: ['Tie: GPT-5.6 Sol · high or Claude Opus 5', 'Sol is excellent for tool-heavy repo work. Opus 5 is excellent for deep implementation and review.'],
  'UI / UX': ['Claude Opus 5', 'Best fit for visual frontend reasoning, UI replication, and iterative polish.'],
  debugging: ['GPT-5.6 Sol · high', 'Use it when the bug spans files, tools, tests, and hidden assumptions.'],
  planning: ['Claude Fable 5', 'Use the deepest model when the plan itself is the hard part.'],
  research: ['Claude Fable 5 or GPT-5.5', 'Fable for synthesis across a huge context. GPT-5.5 for professional research.'],
  'long agent': ['Claude Fable 5', 'Its advantage is sustained instruction following across a long, ambiguous run.'],
  'quick edit': ['GPT-5.3 Codex Spark', 'The fastest choice when the change is narrow and easy to verify.'],
  summarize: ['Claude Haiku 4.5', 'Clear, bounded work does not need a frontier model.'],
}

function fit(model, task) { return task === 'all' ? model.overall : model.tasks.includes(task) ? (model.scores[task] || model.overall) : model.overall - 2 }
function Score({ value }) { return <span className="model-score">{value}/10</span> }

export default function Models() {
  const [task, setTask] = useState('daily default')
  const [query, setQuery] = useState('')
  const [provider, setProvider] = useState('all')
  const [pace, setPace] = useState('all')
  const [sort, setSort] = useState('match')
  const [topOnly, setTopOnly] = useState(false)
  const list = useMemo(() => {
    const term = query.trim().toLowerCase()
    const matches = MODELS.filter(model => {
      const text = [model.name, model.provider, model.badge, model.best, model.copy, model.context, model.thinking, model.price, ...model.tasks].join(' ').toLowerCase()
      return (!term || text.includes(term)) && (provider === 'all' || model.provider === provider) && (pace === 'all' || model.tier === pace) && (!topOnly || fit(model, task) >= 9)
    })
    const value = model => sort === 'speed' ? model.speed : sort === 'value' ? model.value : sort === 'overall' ? model.overall : fit(model, task)
    return matches.sort((a, b) => value(b) - value(a) || b.overall - a.overall)
  }, [pace, provider, query, sort, task, topOnly])
  const [winner, reason] = RECOMMENDATIONS[task]
  return <div className="models-wrap">
    <div className="models-head"><div><div className="eyebrow">Model field guide</div><h2>Pick the model for the actual job.</h2><p>A plain-English cheat sheet for code, UI / UX, debugging, planning, research, speed, tokens, and usage posture.</p></div><div className="models-default"><span>DEFAULT STACK</span><strong>Terra Medium, then High</strong><p>Start with Medium for clear work. Escalate to High for depth, then Sol High or Opus 5 for the genuinely hard cases.</p></div></div>
    <section className="model-effort-guide"><div><div className="model-section-label">Same model, different effort</div><h3>Terra Medium vs High</h3><p>Effort changes how long the model thinks before acting. The model stays the same.</p></div><div className="model-effort-grid"><article><span className="model-effort-tag">Daily default</span><h4>Terra · medium</h4><p><b>Use for:</b> a clear feature, contained bug, UI polish, writing, or a normal plan you will review.</p><small>Choose it when you want a strong answer quickly and can iterate.</small></article><article className="model-effort-high"><span className="model-effort-tag">Deliberate work</span><h4>Terra · high</h4><p><b>Use for:</b> multi-file work, root-cause debugging, risky refactors, architecture tradeoffs, or an important deliverable.</p><small>Choose it when a wrong first take costs more than the wait.</small></article><article><span className="model-effort-tag">Escalate only when needed</span><h4>Sol · high</h4><p><b>Use for:</b> unusually hard, tool-heavy repo work with ambiguous failures, several systems, and test cycles.</p><small>Do not use it for a routine edit just because it is more capable.</small></article></div><div className="model-effort-rule"><b>Simple rule:</b> Clear and bounded = Medium. Multi-step, ambiguous, or expensive to get wrong = High. Still hard after that = Sol High or Opus 5.</div></section>
    <section className="models-start"><div className="model-section-label">Start here</div><h3>What are you doing?</h3><div className="model-task-row">{TASKS.map(([value, label]) => <button key={value} className={`model-task${task === value ? ' active' : ''}`} onClick={() => setTask(value)}>{label}</button>)}</div><div className="model-recommend"><span className="model-best">BEST FIT</span><div><strong>{winner}</strong><p>{reason}</p></div></div></section>
    <section className="model-controls"><label>Search<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="frontend, long context, cheap..." /></label><label>Provider<select value={provider} onChange={e => setProvider(e.target.value)}><option value="all">All providers</option><option>OpenAI</option><option>Anthropic</option></select></label><label>Pace<select value={pace} onChange={e => setPace(e.target.value)}><option value="all">Any pace</option><option value="fast">Fast</option><option value="balanced">Balanced</option><option value="deliberate">Deliberate</option><option value="deep">Deep</option></select></label><label>Sort by<select value={sort} onChange={e => setSort(e.target.value)}><option value="match">Best match</option><option value="overall">Overall capability</option><option value="speed">Speed</option><option value="value">Value</option></select></label><label className="model-check"><input type="checkbox" checked={topOnly} onChange={e => setTopOnly(e.target.checked)} /> Top picks only</label></section>
    <section><div className="model-section-row"><div><div className="model-section-label">The full chart</div><h3>Model cards</h3></div><span className="model-count">{list.length} of {MODELS.length} models</span></div><div className="model-grid">{list.length ? list.map((model, index) => <ModelCard key={model.id} model={model} index={index} task={task} />) : <div className="model-empty">No models match those filters. Clear a filter to see the full chart.</div>}</div></section>
    <section><div className="model-section-row"><div><div className="model-section-label">Side by side</div><h3>Sort the details</h3></div><span className="model-count">Scores are practical guidance, not a benchmark</span></div><div className="model-table-wrap"><table className="model-table"><thead><tr><th>Model</th><th>Best at</th><th>Code</th><th>UI / UX</th><th>Plan</th><th>Debug</th><th>Research</th><th>Speed</th><th>Context</th><th>Typical run</th></tr></thead><tbody>{list.map(model => <tr key={model.id}><td><strong>{model.name}</strong><small>{model.provider} · {model.id}</small></td><td>{model.best}</td><td><Score value={model.scores.code} /></td><td><Score value={model.scores.ui} /></td><td><Score value={model.scores.plan} /></td><td><Score value={model.scores.debug} /></td><td><Score value={model.scores.research} /></td><td className="model-speed">{model.speed}/10</td><td>{model.context}</td><td>{model.session}</td></tr>)}</tbody></table></div></section>
    <footer className="models-foot"><p><b>Timing note:</b> “Typical run” is a practical session budget, not a provider promise. Actual wall time changes with tool calls, repository size, tests, network, model effort, and queueing.</p><p><b>Primary references:</b> <a href="https://developers.openai.com/api/docs/models" target="_blank" rel="noreferrer">OpenAI models</a> · <a href="https://developers.openai.com/api/docs/guides/deployment-checklist#set-up-reasoningeffort" target="_blank" rel="noreferrer">GPT-5.6 effort guidance</a> · <a href="https://platform.claude.com/docs/en/about-claude/models/overview" target="_blank" rel="noreferrer">Claude models</a> · <a href="https://platform.claude.com/docs/en/about-claude/models/whats-new-claude-4-8" target="_blank" rel="noreferrer">Opus 5</a> · <a href="https://platform.claude.com/docs/en/about-claude/models/introducing-claude-fable-5-and-claude-mythos-5" target="_blank" rel="noreferrer">Fable 5</a></p></footer>
  </div>
}

function ModelCard({ model, index, task }) {
  return <article className={`model-card${index === 0 && task !== 'daily default' ? ' model-card-top' : ''}`}><div className="model-card-topline"><span>{model.provider}</span><b>{index < 3 ? `#${index + 1} match` : ''}</b></div><div className="model-title-row"><div><h4>{model.name}</h4><code>{model.id}</code></div><span className="model-badge">{model.badge}</span></div><p className="model-best-for"><b>Best for:</b> {model.best}</p><p className="model-copy">{model.copy}</p><div className="model-facts"><span>Context <b>{model.context}</b></span><span>Output <b>{model.output}</b></span><span>Thinking <b>{model.thinking}</b></span><span>Price posture <b>{model.price}</b></span></div><div className="model-card-foot"><span>Pace <b>{model.pace}</b> · Speed <b>{model.speed}/10</b> · Value <b>{model.value}/10</b></span><span>Typical run <b>{model.session}</b></span></div></article>
}
